######################################################################
# Automatically generated by qmake (3.0) Tue Nov 17 10:20:06 2015
######################################################################

TEMPLATE = app
TARGET = simple
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
