######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 3 09:50:38 2010
######################################################################

TEMPLATE = app
<<<<<<< HEAD
QT+= gui widgets core webengine
=======
QT+= gui widgets core webenginewidgets
>>>>>>> 4269b9d436f770575c045e26185c3f8a18eb3dcb
TARGET = MainWindow
DEPENDPATH += .
INCLUDEPATH += .
CONFIG-=app_bundle
# Input
SOURCES += MainWindow.cpp
macx:QMAKE_MAC_SDK = macosx10.12

