######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 3 09:50:38 2010
######################################################################

TEMPLATE = app
QT+= gui widgets core webkitwidgets
TARGET = MainWindow
DEPENDPATH += .
INCLUDEPATH += .
CONFIG-=app_bundle
# Input
SOURCES += MainWindow.cpp
